// portfolio/client/src/app/components/standard/header/header.component.ts
import { Component } from "@angular/core";

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html'
})

export class HeaderComponent{

}

// const HeaderC = () => {
//   return (

//   );
// };

// export default HeaderC;

<div className="header">
  <nav className="navbar">
    <a className="nav-link" href="/">
      <p>home</p>
    </a>
    <a className="nav-link" href="/about">
      <p>about</p>
    </a>
    <a className="nav-link" href="/portfolio">
      <p>portfolio</p>
    </a>
    <a className="nav-link" href="/contact">
      <p>contact</p>
    </a>
  </nav>
</div>

// portfolio/client/src/components/header.jsx
import React from "react";

const HeaderC = () => {
  return (
    <div className="header">
      <nav className="navbar">
        <a className="nav-link" href="/">
          <p>home</p>
        </a>
        <a className="nav-link" href="/about">
          <p>about</p>
        </a>
        <a className="nav-link" href="/portfolio">
          <p>portfolio</p>
        </a>
        <a className="nav-link" href="/contact">
          <p>contact</p>
        </a>
      </nav>
    </div>
  );
};

export default HeaderC;
