// portfolio/client/src/app/components/admin/home/home.component.ts
import { Component } from "@angular/core";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})

export class AdminHomeComponent{

}

<div class='main'>
  <app-admin-header></app-admin-header>
  <div class='home-page-div'></div>
  <app-admin-footer></app-admin-footer>
</div>

// portfolio/client/src/components/home.jsx
import React from 'react';
import HeaderC from './header';
import FooterC from './footer';


const HomeC = () => {

    return(
        <div className="main">
            <HeaderC/>
            <div className="home-page-div">
            </div>
            <FooterC/>
        </div>
    )
}

export default HomeC;
