// portfolio/client/src/app/components/user/home/home.component.ts
import { Component } from "@angular/core";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})

export class HomeComponent{

}


// import HeaderC from "../../standard/header/header.component";
// import FooterC from "../../standard/footer/footer.component";

// const HomeC = () => {
//   return (

//   );
// };

// export default HomeC;

<div className="main">
  <HeaderC />
  <div className="home-page-div"></div>
  <FooterC />
</div>

// portfolio/client/src/components/home.jsx
import React from 'react';
import HeaderC from './header';
import FooterC from './footer';


const HomeC = () => {

    return(
        <div className="main">
            <HeaderC/>
            <div className="home-page-div">
            </div>
            <FooterC/>
        </div>
    )
}

export default HomeC;
