// portfolio/client/src/app/components/standard/home/home.component.ts
import { Component } from "@angular/core";
// import HeaderC from "../../standard/header/header.component";
// import FooterC from "../../standard/footer/footer.component";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})

export class HomeComponent{

}

<div class='main'>
  <app-header></app-header>
  <div class='home-page-div'></div>
  <app-footer></app-footer>
</div>

// portfolio/client/src/components/home.jsx
import React from 'react';
import HeaderC from './header';
import FooterC from './footer';


const HomeC = () => {

    return(
        <div className="main">
            <HeaderC/>
            <div className="home-page-div">
            </div>
            <FooterC/>
        </div>
    )
}

export default HomeC;
