// portfolio/front-end/src/routes/home.jsx
import React from 'react';
import HomeC from '../components/home';
import FooterC from '../components/footer';
import HeaderC from '../components/header';

const HomeR = () => {
    return(
        <div>
            <HeaderC/>
            <HomeC/>
            <FooterC/>
        </div>
    )
}

export default HomeR;

// portfolio/client/src/app/components/user/home/home.component.ts
import { Component } from "@angular/core";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})

export class HomeComponent{

}


// import HeaderC from "../../standard/header/header.component";
// import FooterC from "../../standard/footer/footer.component";

// const HomeC = () => {
//   return (

//   );
// };

// export default HomeC;

<div className="main">
  <HeaderC />
  <div className="home-page-div"></div>
  <FooterC />
</div>
